language: node_js
node_js:
  - "12.13.0"

install:
  - cd test
  - npm ci


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
    before_install:
      - export DISPLAY=:99
      - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - name: "MacOS"
    os: osx
    script:
      - echo OK.
  - name: "Windows"
    os: windows
    before_install:
      - ls "C:/Program Files/Git/mingw64/libexec/git-core"
      - export PATH=$PATH:"/c/Program Files/Git/mingw64/libexec/git-core"
      - echo $PATH
    script:
      - echo OK.
